on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sample-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sample-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push  # Ensure deployment runs after the image is pushed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@3.252.226.116 << 'EOF'
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/sample-app:latest
            # Stop the existing container if running
            docker stop sample-app || true
            docker rm sample-app || true
            # Run the new container
            docker run -d --name sample-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/sample-app:latest
          EOF
